### PR TITLE
Added ability to clear selected voice in android and iOS

### PR DESCRIPTION
**Pull request by bcaspe**
added a clearVoice method to set any selected voice back to the default voice.

Just a simple change to set the voice to nil in ios and set the voice to defaultVoice in android. I don't know enough about windows development to make the same change there. Help would be appreciated!

### CODE REVIEW

**Comment by bcaspe** [comment]
uh this is embarrasing but I'm not sure how to approve the review? is that something I need to do for my pull request? I can't see that option. Help?

**Review by bcaspe — COMMENTED** [review]
Looks good to me!

**Review by binSaed — APPROVED** [review]

**Review by ckovamees — APPROVED** [review]
I tried these changes and they work on both iOS andAndroid.

**Review by dlutton — APPROVED** [review]
LGTM!

**Pull request merged**
