### PR TITLE
Feature: Added pause function for android

### PR DESCRIPTION
**Pull request by harrowmykel**
Added pause function for Android using suggestions from

https://stackoverflow.com/questions/4970204/how-to-pause-android-speech-tts-texttospeech

### CODE REVIEW

**Comment by harrowmykel** [comment]
Just updated the code again


My previous commit breaks the text into words and reads them one after the other, so that you can pause but that was too slow. 

My new commit should break the the text into sentences by splitting it based on punctuation marks like ? And '.'. If you pause it, it stops and starts from the beginning of the sentence again :)

**Comment by adummy832** [comment]
Pause and resume feature please 🙏

**Comment by harrowmykel** [comment]
@adummy832 Pause is already available at https://github.com/harrowmykel/flutter_tts

use .pause() to pause and .speak() to play

**Comment by harrowmykel** [comment]
@dlutton

**Comment by dlutton** [comment]
@harrowmykel I'll try to get this PR merged in sometime this week

**Comment by dlutton** [comment]
@harrowmykel while testing your changes, I'm continuously receiving null point exceptions.

```
W/Binder  (15050): java.lang.NullPointerException
W/Binder  (15050):      at com.tundralabs.fluttertts.FlutterTtsPlugin$utteranceProgressListener$1.onProgress(FlutterTtsPlugin.kt:142)
W/Binder  (15050):      at com.tundralabs.fluttertts.FlutterTtsPlugin$utteranceProgressListener$1.onRangeStart(FlutterTtsPlugin.kt:164)
```

**Comment by mo-aro-etailer** [comment]
@dlutton This issue has been fixed. Thanks for letting me know

**Comment by harrowmykel** [comment]
@dlutton

**Comment by dlutton** [comment]
thanks @mo-aro-etailer , I'll take a look at it soon and get it merged in.

**Pull request merged**
