### PR TITLE
Add callbacks on Windows platform

### PR DESCRIPTION
**Pull request by vagoston**
Related issue: https://github.com/dlutton/flutter_tts/issues/326
This change adds implementation for the missing callbacks on start, pause, continue, cancel and completion. 
Callbacks for onError and onProgress are still missing, I don't even understand how/if onProgress would work on Windows.

### CODE REVIEW

**Review by dlutton — COMMENTED** [review]
LGTM

**Review by dlutton — APPROVED** [review]

**Comment by dlutton** [comment]
thanks @vagoston, I'll get this published with a new version soon.

**Comment by vagoston** [comment]
@dlutton I see that the build is broken, but I don't think it's related to my changes. Let me know if I should fix something.
```
Target dart2js failed: Exception: Warning: The 'dart2js' entrypoint script is deprecated, please use 'dart compile js' instead.
../_flutter/bin/cache/flutter_web_sdk/lib/ui/geometry.dart:37:[16](https://github.com/dlutton/flutter_tts/actions/runs/3174804297/jobs/5172052607#step:5:17):
Error: The 'super-parameters' language feature is disabled for this library.
  const Offset(super.dx, super.dy);
               ^^^^^
```

**Comment by dlutton** [comment]
I agree, it appears to be unrelated and I'll attempt to fix it.

**Pull request merged**
